#!/bin/bash

# Function definition with parameters
mange() {
  local namespace="$1"
  local repo="$2"
  local rows="$3"
  local method="${4:-parquet}"

  echo "namespace ..: $namespace"
  echo "repo name ..: $repo"
  echo "row count ..: $rows"
  echo "method .....: $method"

  rm -fr "/data2/mvdata/data/${namespace}_${repo}/*.{method}"

  python3 mange_csv.py \
  --output="/data2/mvdata/data/${namespace}_${repo}" \
  --rows=$rows \
  --method="${method}" \
  --file="/data2/github-slurp/data/${namespace}_${repo}/${repo}_issues.csv"

  python3 mange_csv.py \
  --output="/data2/mvdata/data/${namespace}_${repo}" \
  --rows=$rows \
  --method="${method}" \
  --file="/data2/github-slurp/data/${namespace}_${repo}/${repo}_pull_requests.csv"

}

cd /data2/github-slurp
source .venv/bin/activate
cd /data2/github-slurp/helpers

mange "frappe" "erpnext" 180000
mange "tensorflow" "tensorflow" 180000
mange "odoo" "odoo" 180000
mange "metabase" "metabase" 180000
mange "apache" "airflow" 180000
mange "pytorch" "pytorch" 180000
mange "kubernetes" "kubernetes" 180000
mange "OWASP" "Nettacker" 180000

cd /data2/mvdata
git add .
git commit -am 'data encode parquet'
git push
